# Generated by Django 4.2.5 on 2024-02-04 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('UserAuth', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.CharField(default='DefaultJobID', max_length=255, unique=True)),
                ('title', models.CharField(default='Default Job Title', max_length=200)),
                ('company_name', models.CharField(default='Default Company', max_length=200)),
                ('location', models.CharField(default='Default Location', max_length=200)),
                ('job_description', models.TextField(default='Default Job Description')),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Applicant', 'Applicant')], default='Applicant', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userauth_permission_set', related_query_name='userauth_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='JobToSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillID', models.CharField(default='DefaultSkillID', max_length=255, unique=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='UserAuth.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirementID', models.CharField(default='DefaultReqID', max_length=255, unique=True)),
                ('description', models.TextField(default='Default Requirement Description')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='UserAuth.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeID', models.CharField(default='DefaultTypeID', max_length=255, unique=True)),
                ('type_name', models.CharField(default='Default Employment Type', max_length=200)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_type', to='UserAuth.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefitID', models.CharField(default='DefaultBenefitID', max_length=255, unique=True)),
                ('description', models.TextField(default='Default Benefit Description')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='UserAuth.jobposting')),
            ],
        ),
    ]
