# Generated by Django 4.2.5 on 2024-02-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_jobposting_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience_required',
            field=models.CharField(blank=True, default='No experience required', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_postings', to='UserAuth.listofskills'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
