# Generated by Django 4.2.5 on 2024-02-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0007_remove_benefits_benefitid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='educationID',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resumeID',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='experienceID',
        ),
    ]
