# Generated by Django 4.2.5 on 2024-02-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0008_remove_education_educationid_remove_resume_resumeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetoskills',
            name='skillID',
            field=models.CharField(default='DefaultSkillID', max_length=255),
        ),
    ]
