# Generated by Django 4.2.5 on 2024-02-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0008_remove_education_educationid_remove_resume_resumeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobToCluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobPosting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserAuth.jobposting')),
            ],
        ),
    ]
