# Generated by Django 4.2.5 on 2024-02-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0009_jobtocluser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobToCluser',
            new_name='JobToCluster',
        ),
    ]
