# Generated by Django 4.2.5 on 2024-02-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0009_alter_resumetoskills_skillid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetoskills',
            old_name='skillID',
            new_name='skill_name',
        ),
    ]
