# Generated by Django 4.2.5 on 2024-02-24 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0011_delete_jobtoclusters'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobToClusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cluster', to='UserAuth.jobposting')),
            ],
        ),
    ]
