# Generated by Django 4.2.5 on 2024-02-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0013_jobtoclusters_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtoclusters',
            name='cluster',
            field=models.CharField(default='defaultcluster', max_length=255),
        ),
    ]
