# Generated by Django 4.2.5 on 2024-03-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0010_rename_jobtocluser_jobtocluster'),
        ('UserAuth', '0010_rename_skillid_resumetoskills_skill_name'),
        ('UserAuth', '0015_feedback'),
    ]

    operations = [
    ]
