# Generated by Django 4.2.5 on 2024-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0017_feedbackforjob_feedbackforresume_modelversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenttype',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='jobrequirements',
            name='job_posting',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Benefits',
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
        migrations.DeleteModel(
            name='JobRequirements',
        ),
    ]
