# Generated by Django 4.2.5 on 2024-03-13 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0019_remove_jobposting_creator_jobposting_user'),
    ]

    operations = [

        migrations.CreateModel(
            name='FeedbackforResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='0', max_length=255)),
                ('score', models.CharField(default='0', max_length=255)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_resume', to='UserAuth.jobposting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.AddField(
            model_name='jobposting',
            name='skills_list',
            field=models.JSONField(default=list),
        )
    ]
