# Generated by Django 4.2.5 on 2024-03-22 17:21

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0020_feedbackforresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills_list',
            field=models.JSONField(default=list),
        )
    ]
