# Generated by Django 4.2.5 on 2024-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0021_delete_jobtoskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='cluster',
            field=models.IntegerField(default=0, max_length=255),
        ),

    ]
